<?xml version="1.0" encoding="utf-8"?><Database Name="POSNew12" Class="POSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ROBIN\SQLEXPRESS;Initial Catalog=POSNew12;Integrated Security=True;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="Point_of_Sale_Orpa_Telecom_v3.Properties.Settings" SettingsPropertyName="POSNew12ConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AddressLine" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Postal_Code" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Phone1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Address_Employee" Member="Employees" ThisKey="ID" OtherKey="Address_ID" Type="Employee" />
      <Association Name="Address_Login" Member="Logins" ThisKey="ID" OtherKey="Address_ID" Type="Login" />
      <Association Name="Address_Supplier" Member="Suppliers" ThisKey="ID" OtherKey="Address_ID" Type="Supplier" />
    </Type>
  </Table>
  <Table Name="dbo.Barcode" Member="Barcodes">
    <Type Name="Barcode">
      <Column Name="Barcode_Serial" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Product_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Barcode_Gift" Member="Gift" ThisKey="Barcode_Serial" OtherKey="Barcode" Type="Gift" Cardinality="One" />
      <Association Name="Product_Barcode" Member="Product" ThisKey="Product_ID" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Phone2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Customer_Sale" Member="Sales" ThisKey="ID" OtherKey="Customer_ID" Type="Sale" />
    </Type>
  </Table>
  <Table Name="dbo.Customer_Sale" Member="Customer_Sales">
    <Type Name="Customer_Sale">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Invoice_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Unit_Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sold_Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sale_Price_was" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sold_By" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Customer_Sale_Gift" Member="Gifts" ThisKey="ID" OtherKey="Customer_Sale_ID" Type="Gift" />
      <Association Name="Login_Customer_Sale" Member="Login" ThisKey="Sold_By" OtherKey="Username" Type="Login" IsForeignKey="true" />
      <Association Name="Product_Customer_Sale" Member="Product" ThisKey="Product_ID" OtherKey="ID" Type="Product" IsForeignKey="true" />
      <Association Name="Sale_Customer_Sale" Member="Sale" ThisKey="Invoice_ID" OtherKey="Invoice_ID" Type="Sale" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Last_Login" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="User_Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Manager_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Employee" Member="Employees" ThisKey="ID" OtherKey="Manager_ID" Type="Employee" />
      <Association Name="Employee_Login" Member="Logins" ThisKey="ID" OtherKey="Manager_ID" Type="Login" />
      <Association Name="Address_Employee" Member="Address" ThisKey="Address_ID" OtherKey="ID" Type="Address" IsForeignKey="true" />
      <Association Name="Employee_Employee" Member="Employee1" ThisKey="Manager_ID" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Free_Product" Member="Free_Products">
    <Type Name="Free_Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Invoice_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Free_Product" Member="Product" ThisKey="Product_ID" OtherKey="ID" Type="Product" IsForeignKey="true" />
      <Association Name="Sale_Free_Product" Member="Sale" ThisKey="Invoice_ID" OtherKey="Invoice_ID" Type="Sale" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Gift" Member="Gifts">
    <Type Name="Gift">
      <Column Name="Barcode" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Customer_Sale_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SL" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
      <Column Name="[Gift Code]" Member="Gift_Code" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
      <Column Name="[Discount Price]" Member="Discount_Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Barcode_Gift" Member="Barcode1" ThisKey="Barcode" OtherKey="Barcode_Serial" Type="Barcode" IsForeignKey="true" />
      <Association Name="Customer_Sale_Gift" Member="Customer_Sale" ThisKey="Customer_Sale_ID" OtherKey="ID" Type="Customer_Sale" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Journal" Member="Journals">
    <Type Name="Journal">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sub_Account_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreparedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AuthenticatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Journal_Journal_Detail" Member="Journal_Details" ThisKey="ID" OtherKey="Journal_ID" Type="Journal_Detail" />
      <Association Name="Journal_Product_Supplier" Member="Product_Suppliers" ThisKey="ID" OtherKey="Journal_ID" Type="Product_Supplier" />
      <Association Name="Journal_Sale" Member="Sales" ThisKey="ID" OtherKey="Journal_ID" Type="Sale" />
      <Association Name="Journal_Support" Member="Supports" ThisKey="ID" OtherKey="Voucher_ID" Type="Support" />
      <Association Name="Journal_Payment" Member="Payments" ThisKey="ID" OtherKey="Journal_ID" Type="Payment" />
      <Association Name="Login_Journal" Member="Login" ThisKey="AuthenticatedBy" OtherKey="ID" Type="Login" IsForeignKey="true" />
      <Association Name="Login_Journal1" Member="Login1" ThisKey="PreparedBy" OtherKey="ID" Type="Login" IsForeignKey="true" />
      <Association Name="Sub_Account_Journal" Member="Sub_Account" ThisKey="Sub_Account_ID" OtherKey="ID" Type="Sub_Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Journal_Details" Member="Journal_Details">
    <Type Name="Journal_Detail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Journal_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sub_Account_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Narration" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Journal_Journal_Detail" Member="Journal" ThisKey="Journal_ID" OtherKey="ID" Type="Journal" IsForeignKey="true" />
      <Association Name="Sub_Account_Journal_Detail" Member="Sub_Account" ThisKey="Sub_Account_ID" OtherKey="ID" Type="Sub_Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Login" Member="Logins">
    <Type Name="Login">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Last_Login" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="User_Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Manager_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Login_Customer_Sale" Member="Customer_Sales" ThisKey="Username" OtherKey="Sold_By" Type="Customer_Sale" />
      <Association Name="Login_Journal" Member="Journals" ThisKey="ID" OtherKey="AuthenticatedBy" Type="Journal" />
      <Association Name="Login_Journal1" Member="Journals1" ThisKey="ID" OtherKey="PreparedBy" Type="Journal" />
      <Association Name="Address_Login" Member="Address" ThisKey="Address_ID" OtherKey="ID" Type="Address" IsForeignKey="true" />
      <Association Name="Employee_Login" Member="Employee" ThisKey="Manager_ID" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Main_Accounts" Member="Main_Accounts">
    <Type Name="Main_Account">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Catagory" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Main_Account_Sub_Account" Member="Sub_Accounts" ThisKey="ID" OtherKey="Main_Accounts_ID" Type="Sub_Account" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Quantity_Available" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity_Sold" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Unit_Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Selling_Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Des" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="Date_Updated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Unique_Barcode" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Association Name="Product_Barcode" Member="Barcodes" ThisKey="ID" OtherKey="Product_ID" Type="Barcode" />
      <Association Name="Product_Customer_Sale" Member="Customer_Sales" ThisKey="ID" OtherKey="Product_ID" Type="Customer_Sale" />
      <Association Name="Product_Free_Product" Member="Free_Products" ThisKey="ID" OtherKey="Product_ID" Type="Free_Product" />
      <Association Name="Product_Product_Supplier" Member="Product_Suppliers" ThisKey="ID" OtherKey="Product_ID" Type="Product_Supplier" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Supplier" Member="Product_Suppliers">
    <Type Name="Product_Supplier">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ref_Number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Product_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Supplier_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Journal_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Unit_Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Journal_Product_Supplier" Member="Journal" ThisKey="Journal_ID" OtherKey="ID" Type="Journal" IsForeignKey="true" />
      <Association Name="Product_Product_Supplier" Member="Product" ThisKey="Product_ID" OtherKey="ID" Type="Product" IsForeignKey="true" />
      <Association Name="Supplier_Product_Supplier" Member="Supplier" ThisKey="Supplier_ID" OtherKey="ID" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sales" Member="Sales">
    <Type Name="Sale">
      <Column Name="Invoice_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Customer_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Journal_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Sale_Customer_Sale" Member="Customer_Sales" ThisKey="Invoice_ID" OtherKey="Invoice_ID" Type="Customer_Sale" />
      <Association Name="Sale_Free_Product" Member="Free_Products" ThisKey="Invoice_ID" OtherKey="Invoice_ID" Type="Free_Product" />
      <Association Name="Customer_Sale" Member="Customer" ThisKey="Customer_ID" OtherKey="ID" Type="Customer" IsForeignKey="true" />
      <Association Name="Journal_Sale" Member="Journal" ThisKey="Journal_ID" OtherKey="ID" Type="Journal" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sub_Accounts" Member="Sub_Accounts">
    <Type Name="Sub_Account">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Main_Accounts_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Sub_Account_Journal" Member="Journals" ThisKey="ID" OtherKey="Sub_Account_ID" Type="Journal" />
      <Association Name="Sub_Account_Journal_Detail" Member="Journal_Details" ThisKey="ID" OtherKey="Sub_Account_ID" Type="Journal_Detail" />
      <Association Name="Main_Account_Sub_Account" Member="Main_Account" ThisKey="Main_Accounts_ID" OtherKey="ID" Type="Main_Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Address_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Company_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contact_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contact_Designation" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Supplier_Product_Supplier" Member="Product_Suppliers" ThisKey="ID" OtherKey="Supplier_ID" Type="Product_Supplier" />
      <Association Name="Address_Supplier" Member="Address" ThisKey="Address_ID" OtherKey="ID" Type="Address" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Support" Member="Supports">
    <Type Name="Support">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Voucher_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Journal_Support" Member="Journal" ThisKey="Voucher_ID" OtherKey="ID" Type="Journal" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Payment_For_Whom" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Payment_For_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Journal_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Journal_Payment" Member="Journal" ThisKey="Journal_ID" OtherKey="ID" Type="Journal" IsForeignKey="true" />
    </Type>
  </Table>
</Database>